gpu_id: 2
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expGQAFullsetLOGNet'

train:
  lr: 0.0001
  batch_size: 64
  restore: False
  epoch_decay_half: 10
  max_epochs: 30
  word_dim: 300
  vision_dim: 2048
  module_dim: 512
  glove: True
  train_num: 0
  net_length: 12
  control_input_unshared: True
  weight_init: "xavier_uniform"

val:
  flag: True
  is_vis: False
  write_preds: False
  batch_size: 64
  val_num: 0

test:
  test_num: 0
  write_preds: True

dataset:
  name: 'gqa'
  annotation_file: '/AvaStore/DataSets/visual_qa/datasets/gqa/annotations/{}_balanced_questions.json'
  img_info: 'gqa_objects_merged_info.json'
  data_dir: 'data/'
  train_feature: 'gqa_objects.h5'
  val_feature: 'gqa_objects.h5'
  test_feature: 'gqa_objects.h5'
  train_question: 'gqa_train_questions.pt'
  val_question: 'gqa_val_questions.pt'
  test_question: 'gqa_test_questions.pt'
  vocab_json: 'gqa_vocab.json'
  save_dir: 'results/'

preprocess:
  glove_pt: '/AvaStore/DataSets/visual_qa/datasets/glove/glove.840.300d.pkl'